version: "3"

services:
  stdouter:
    image: adamryman/fsrestarter
    volumes:
    - $GOPATH/src/github.com/adamryman/restarter/test/target:/target
    command: ["-i", "echo 123", "--", "/target/run", "-n", "0.5s"]
    #entrypoint: "echo"
    environment:
      - RESTARTER_DEBUG=1
