version: "3"

services:
  stdouter:
    image: adamryman/fsrestarter
    volumes:
    - $GOPATH/src/github.com/adamryman/restarter/test/target:/target
    command: ["/target/run", "-n", "0.5s"]
    environment:
      - RESTARTER_DEBUG=1
